apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv3
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv3"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv4
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv4"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv5
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv5"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv6
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv6"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv7
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv7"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv8
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/pv8"

