apiVersion: v1
kind: Service
metadata:
  name: redis-share-service
  labels:
    app: redis-share
spec:
  ports:
  - name: redis-share-port
    port: 6379
  clusterIP: None
  selector:
    app: redis-share
    appCluster: redis-share-cluster
