apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share"
