apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv1
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv2
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv3
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv3"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv4
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv4"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv5
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv5"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv6
spec:
  capacity:
    storage: 1200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.148
    path: "/root/nfs/share/pv6"
